# Generated by Django 4.2 on 2023-04-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleslatest',
            name='body_html',
            field=models.CharField(null=True),
        ),
    ]
